spring.datasource.url=db.fpeqjarcbboexsmszawf.supabase.co
spring.datasource.username=postgres
spring.datasource.password=ProTeam@2025
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true